version: "3"
services:
    database:
        image: "postgres:13.4"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: ${BACKEND_DB_USER}
            POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ../data/postgres-pet_library:/var/lib/postgresql/data/
        networks:
            - pet_library
        ports:
            - 127.0.0.1:5434:5432
        restart: always
networks:
    pet_library:
    public_lib:
        external: true
